### ISSUE TITLE
amsmath中的 \underbrace 显示错误

### ISSUE THREAD

**Issue by hdchieh** [chenkenbio/sysu-graduate-thesis#3]
## 编译环境
编译的系统：Windows 10
TeX 发行版：TeX Live 2021
模板版本：36a09e1
模板类型：master

## 描述问题
\underbrace 显示错误

截图：
![image](https://user-images.githubusercontent.com/33096672/149857486-b128cd05-f445-45d0-939a-16d03e86dd10.png)
期望结果：
![image](https://user-images.githubusercontent.com/33096672/149857675-749247ec-c0a2-4e15-a996-750d7af792eb.png)

复现上述问题的代码：
```TeX
\begin{align}
    {a}_{i, j}^{\mathrm{rel}} &=\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, E} {E}_{x_{j}}}_{(a)}+\underbrace{{E}_{x_{i}}^{\top} {W}_{q}^{\top} {W}_{k, R} {R}_{i-j}}_{(b)} \nonumber\\
    &+\underbrace{u^{\top} {W}_{k, E} {E}_{x_{j}}}_{(c)}+\underbrace{v^{\top} {W}_{k, R} {R}_{i-j}}_{(d)}\text{,} 
\end{align}
```

**Comment by zepinglee** [comment]
可能跟 `mathtools` 的载入顺序有关。参考 https://github.com/tuna/thuthesis/commit/caea9cc6b861a1164abf1225d5c127877b52ada3 和 <https://tex.stackexchange.com/q/521394/82731>。

**Comment by hdchieh** [comment]
> 可能跟 `mathtools` 的载入顺序有关。参考 https://github.com/tuna/thuthesis/commit/caea9cc6b861a1164abf1225d5c127877b52ada3 和 <https://tex.stackexchange.com/q/521394/82731>。

谢谢🙏，sysuthesis.dtx对比thuthesis这个库确实缺少了提前载入 'mathtools'。😭您也太勤劳了。
